// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEt76-taH8yTXjtyEGQUoBUoqc02SfVwo',
    appId: '1:158341961420:web:d73210bbd2d52970905469',
    messagingSenderId: '158341961420',
    projectId: 'stage-f1169',
    authDomain: 'stage-f1169.firebaseapp.com',
    storageBucket: 'stage-f1169.appspot.com',
    measurementId: 'G-QL2XPNNCZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7FW_uZnKMcO4ceHmNvVWgNxFxp-yQShE',
    appId: '1:158341961420:android:93c57082d645883a905469',
    messagingSenderId: '158341961420',
    projectId: 'stage-f1169',
    storageBucket: 'stage-f1169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuoQm_RuMsDbI1rwI8hkhWjwgjYiBYueg',
    appId: '1:158341961420:ios:e53ca4c3d8ed6ffc905469',
    messagingSenderId: '158341961420',
    projectId: 'stage-f1169',
    storageBucket: 'stage-f1169.appspot.com',
    iosBundleId: 'com.aliret.fitfood',
  );
}
